server:
  port: 9991


spring:
  application:
    # 指定应用名称，如果没有传递就使用hello-sb
    name: "${appName: hello-sb}"

# 自定义配置 演示不同profile装配不同bean
ml:
  study:
    storage:
      type: local
      uName: admin
      pwd: 123123
